Repository hmcts/sptribs-dss-update-case-web, pull requests merged in 2024-03, with the labels that each got.

#88 DTSSTCI-355
  src/main/modules/oidc/index.ts
  src/main/routes/authless/routes.ts
  src/main/steps/dss-update/confirmation-page/content.test.ts
  src/main/steps/dss-update/confirmation-page/content.ts
  src/main/steps/dss-update/confirmation-page/postController.test.ts
  src/main/steps/dss-update/confirmation-page/postController.ts
  src/main/steps/dss-update/confirmation-page/template.njk
  src/main/steps/dss-update/subject-details/postController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-88

#87 DTSSTCI-545
  config/development.yaml
  package.json
  src/main/assets/js/cookie.ts
  src/main/steps/common/common.content.ts
  src/main/steps/cookie-banner/template.njk
  yarn.lock
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-87

#117 Bump terraform-provider-azurerm to latest version 3.95.0
  infrastructure/state.tf
Labels: ns:sptribs, prd:sptribs, no-changes, rel:sptribs-dss-update-case-web-pr-117

#101 DTSSTCI-353 and DTSSTCI-450
  config/default.yaml
  config/development.yaml
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/fileUpload/documentManager.test.ts
  src/main/app/fileUpload/documentManager.ts
  src/main/steps/upload-documents/content.test.ts
  src/main/steps/upload-documents/content.ts
  src/main/steps/upload-documents/getController.test.ts
  src/main/steps/upload-documents/getController.ts
  src/main/steps/upload-documents/postController.test.ts
  src/main/steps/upload-documents/postController.ts
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-101

#102 DTSSTCI-558
  src/main/steps/common/common.content.ts
  src/main/steps/cookies/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-102

#109 DTSSTCI-557
  charts/sptribs-dss-update-case-web/Chart.yaml
  charts/sptribs-dss-update-case-web/values.yaml
  config/default.yaml
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/authless/landing/landing.njk
  src/main/steps/common/page.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-109

#97 DTSSTCI-467
  package.json
  sonar-project.properties
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-97

#122 DTSSTCI-640
  sonar-project.properties
  src/main/modules/appinsights/index.test.ts
  src/main/modules/fileupload/index.test.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/upload-documents/postController.test.ts
  src/main/steps/upload-documents/postController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-122

#125 DTSSTCI-640 v2
  sonar-project.properties
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/helmet/index.test.ts
  src/main/modules/oidc/index.test.ts
  src/main/steps/upload-documents/getController.test.ts
  src/main/steps/upload-documents/getController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-125

#126 DTSSTCI-640 v3
  package.json
  src/main/steps/upload-documents/postController.test.ts
  src/main/steps/upload-documents/postController.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-126

#52 DTSSTCI-354
  src/main/steps/dss-update/check-your-answers/content.test.ts
  src/main/steps/dss-update/check-your-answers/content.ts
  src/main/steps/dss-update/check-your-answers/form.njk
  src/main/steps/dss-update/check-your-answers/postController.ts
  src/main/steps/dss-update/check-your-answers/template.njk
  src/main/steps/dss-update/check-your-answers/utils.test.ts
  src/main/steps/dss-update/check-your-answers/utils.ts
Labels: ns:sptribs, prd:sptribs, no-changes, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-52

#86 DTSSTCI-432
  src/main/modules/nunjucks/index.ts
  src/main/routes/authless/landing/content.json
  src/main/routes/authless/landing/landing.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/dss-update/confirmation-page/content.test.ts
  src/main/steps/dss-update/confirmation-page/content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-86

#85 DTSSTCI-449
  src/main/steps/common/common.content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-85

#129 DTSSTCI-396
  charts/sptribs-dss-update-case-web/Chart.yaml
  charts/sptribs-dss-update-case-web/values.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-129

#120 DTSSTCI-574
  config/default.yaml
  config/development.yaml
  src/main/modules/fileupload/index.test.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-120

#128 DTSSTCI-663
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-128

#130 DTSSTCI-396
  charts/sptribs-dss-update-case-web/Chart.yaml
  charts/sptribs-dss-update-case-web/values.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-130

#132 DTSSTCI-395
  charts/sptribs-dss-update-case-web/Chart.yaml
  charts/sptribs-dss-update-case-web/values.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-132

#133 DTSSTCI-663: Investigate timeout errors
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-133

#123 DTTSTCI-413
  src/main/app/case/api.ts
  src/main/app/case/case.ts
  src/main/app/controller/AppRequest.ts
  src/main/steps/dss-update/casefinder/postController.test.ts
  src/main/steps/dss-update/check-your-answers/content.test.ts
  src/main/steps/dss-update/check-your-answers/content.ts
  src/main/steps/dss-update/check-your-answers/postController.test.ts
  src/main/steps/dss-update/check-your-answers/postController.ts
  src/main/steps/dss-update/check-your-answers/utils.ts
  src/main/steps/dss-update/subject-details/postController.test.ts
  src/main/steps/upload-documents/postController.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-123

#124 DTSSTCI-660
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/modules/oidc/index.test.ts
  src/main/modules/oidc/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/dss-update/subject-details/content.test.ts
  src/main/steps/timed-out/content.ts
  src/main/steps/timed-out/get.test.ts
  src/main/steps/timed-out/get.ts
  src/main/steps/timed-out/template.njk
  src/main/steps/url-utils.test.ts
  src/main/steps/url-utils.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-124

#134 DTSSTCI-663
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-134

#131 DTSSTCI-666
  src/main/app/auth/oidc.test.ts
  src/main/app/auth/oidc.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/oidc/index.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-131

#139 Potential fix for master pipeline
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-139

#143 Resolve CVE for express package
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-143
