Repository hmcts/sptribs-dss-update-case-web, pull requests merged in 2024-06, with the labels that each got.

#261 DTSSTCI-843
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/upload-documents/content.test.ts
  src/main/steps/upload-documents/content.ts
  src/main/steps/upload-documents/postController.test.ts
  src/main/steps/upload-documents/postController.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-261

#253 DTSSTCI-839
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-253

#337 DTSSTCI-880
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-337

#342 DTSSTCI-882
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-342

#339 DTSSTCI-748
  src/main/steps/accessibility-statement/content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-339

#338 DTSSTCI-747
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/no-changes, prod/no-changes, rel:sptribs-dss-update-case-web-pr-338
