Repository hmcts/sptribs-dss-update-case-web, pull requests merged in 2024-05, with the labels that each got.

#232 Add module package to sonar exclusions
  sonar-project.properties
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-232

#234 Refactor code to resolve sonarqube issue
  src/main/steps/upload-documents/getController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-234

#227 DTSSTCI-763
  src/main/steps/dss-update/subject-details/content.test.ts
  src/main/steps/dss-update/subject-details/content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-227

#237 DTSSTCI-758
  charts/sptribs-dss-update-case-web/values.preview.template.yaml
  src/main/server.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-237

#233 DTSSTCI-728
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/no-changes, rel:sptribs-dss-update-case-web-pr-233

#222 DTSSTCI-725
  src/main/assets/scss/main.scss
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/no-changes, rel:sptribs-dss-update-case-web-pr-222

#228 DTSSTCI-750
  Jenkinsfile_nightly
  package.json
  src/test/java/.gitignore
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
  src/test/java/settings.gradle
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-228

#249 Disable spot instances in values.yaml
  charts/sptribs-dss-update-case-web/Chart.yaml
  charts/sptribs-dss-update-case-web/values.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-249

#226 DTSSTCI-745
  codecept.conf.js
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-226

#238 DTSSTCI-727
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/dss-update/subject-details/content.test.ts
  src/main/steps/dss-update/subject-details/content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-238

#251 Fixing nightly pipelines
  Jenkinsfile_nightly
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-251

#271 DTSSTCI-853: Added prod.tfvars - infrastructure change
  Jenkinsfile_CNP
  infrastructure/prod.tfvars
Labels: ns:sptribs, prd:sptribs, aat/no-changes, rel:sptribs-dss-update-case-web-pr-271, prod/no-changes
