Repository hmcts/sptribs-dss-update-case-web, pull requests merged in 2024-04, with the labels that each got.

#150 Bump version of Chai testing framework to latest
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-150

#152 Resolve Sonarqube failing on master branch
  src/main/modules/oidc/index.ts
  src/main/steps/upload-documents/getController.test.ts
  src/main/steps/upload-documents/getController.ts
  src/test/unit/mocks/mockRequest.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-152

#151 DTSSTCI-734
  .dockerignore
  .swcrc
  jest.a11y.config.js
  jest.config.js
  jest.smoke.config.js
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-151

#157 Remove redundant user details object from oidc class
  src/main/app/auth/oidc.test.ts
  src/main/app/auth/oidc.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-157

#168 DTSSTCI-322
  src/main/assets/js/go-back.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-168

#186 DTSSTCI-720
  src/main/steps/dss-update/check-your-answers/form.njk
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-186

#183 DTSSTCI-721
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-183

#181 DTSSTCI-272
  src/main/steps/dss-update/check-your-answers/utils.test.ts
  src/main/steps/dss-update/check-your-answers/utils.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/no-changes, rel:sptribs-dss-update-case-web-pr-181

#187 DTSSTCI-720
  src/main/steps/dss-update/check-your-answers/form.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/no-changes, rel:sptribs-dss-update-case-web-pr-187

#207 Resolve downstream cve issue with formidable in hmcts/nodejs-logging package
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-207

#202 DTSSTCI-722
  src/main/steps/upload-documents/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-202

#201 DTSSTCI-758
  src/main/server.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-201

#223 Update stryker package
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-dss-update-case-web-pr-223

#213 DTSSTCI-755
  config/default.yaml
  src/main/modules/fileupload/index.test.ts
  src/main/steps/upload-documents/content.test.ts
  src/main/steps/upload-documents/content.ts
  src/main/steps/upload-documents/postController.test.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/no-changes, rel:sptribs-dss-update-case-web-pr-213

#221 DTSSTCI-744
  src/main/steps/privacy-policy/content.test.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-dss-update-case-web-pr-221
